### ISSUE TITLE
Help with function-nize the last pannel

### ISSUE THREAD

**Issue by LienDNguyen** [LienDNguyen/calcium_imaging#5]
I managed to label both traces in the mean graph, but can't wrap the whole thing in a function.

Also, tried to use sns.tsplot for the data, but then the data structure has to be really weird. And sns.lineplot wasn't available.

I did try stuff though.

**Comment by LienDNguyen** [comment]
Also, what I attempted to do:
Generate a time column, e.g. index/4 --> unit = second
Join time column to ctrl/ L89A data using .join --> after index, first column of dataframe is the time column, then all columns after that are signals of individual cells

Use a smart plot function that somehow knows that the time column is x, and then average out the rest to give the average trace, with SD or SEM or 95 CI error bar.

Will try some more tomorrow, and implement area under the curve.

**Comment by DanielSchuette** [comment]
I'll look into it and if I find a fix, I'll upload another workbook with the working code included. It's related to the most recent workbook in the `code` folder, correct?

**Comment by LienDNguyen** [comment]
Yes, should be the 20180918_calcium_imaging.ipynb, and the last panel  of that file.

**Comment by DanielSchuette** [comment]
I created a new dataframe that has the correct input format for a `seaborn.lineplot`. I hope that is what you wanted. But, since you used the `mean` data as an input, the error bars are virtually non-existent. I would suggest to use the raw data (that has the `F/F0` for all cell lines) for this particular plot. `seaborn.lineplot` will take care of calculating the means and CI's for us. You would have a data frame like this:

| time | F/F0 | coverslip | cell_number | genotype |
| ---- | ----- | --------- | ------------ | --------- |
| 0.25 | 1.14 |                1 |                    1 | CTRL       |
| ...     | ...     | ...              | ...                   | ...             |
